spring:
  application:
    name: conferences
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: dockerpg13
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 10
      connection-test-query: SELECT 1
      pool-name: conferences-db-cp
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
    open-in-view: false
    show-sql: true
  mvc:
    throw-exception-if-no-handler-found: true
logging:
  file:
    name: conferences.log